import sys
import time
import logging
import numpy as np, numpy.random
import random
import os
import torch
from sklearn.metrics.pairwise import cosine_similarity
from cover_tree import CoverTree
import shutil

def set_logger(name, timestamp):
    formatter=logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    logger=logging.getLogger(f'{name}-Logger')
    file_handler=logging.FileHandler(f'./log-{name}-{timestamp}.log')
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
    console_handler=logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)
    logger.setLevel(logging.INFO)
    return logger

def set_seed(args):
    random.seed(args.seed) 
    np.random.seed(args.seed) 
    torch.manual_seed(args.seed) 
    if torch.cuda.is_available(): 
        torch.cuda.manual_seed_all(args.seed) 

def gen_data(trainloader, testloader, m):
    """
    This function generate data with new labels.
    New labels are generated by adding a new number which selected uniformly at random from [number].
    """
    sim = gen_sim(m)
    examples = enumerate(trainloader)

    train_data = []
    train_label = []
    train_original = []
    while True:
        try:
            batch_idx, (example_data, example_targets) = next(examples)
            label = example_targets.numpy()
            train_original.append(example_targets)
            new_train = np.random.choice(np.arange(0,m.shape[0]), p = np.transpose(m[:,label]).flatten())
            train_label.append(new_train)
            train_data.append(example_data.squeeze(0).numpy())
        except:
            break

    instances = enumerate(testloader)

    test_data = []
    test_label = []
    original_label = []
    while True:
        try:
            batch_index, (instances_data, instances_targets) = next(instances)
            label = instances_targets.numpy()
            original_label.append(instances_targets)
            new_test = np.random.choice(np.arange(0,m.shape[0]), p = np.transpose(m[:,label]).flatten())
            test_label.append(new_test)
            test_data.append(instances_data.squeeze(0).numpy())
        except:
            break

    return train_data, train_label, train_original, test_data, test_label, original_label, sim

def gen_matrix(num_label, num_new, n):
    """
    This function get distribution of new labels.
    The input are number of original labels and number of new labels we want to create.
    It returns a matrix of shape ba (where a is the number of classes in the original dataset and b is the number of new classes we're creating;
    """
    m = np.zeros((num_new, num_label))
    p = np.random.dirichlet(np.ones(n),size=1)
    for i in range(num_label):
        for j in range(n):
            m[i,i+j-n-1] = p[0][j]
    return m


def gen_sim(m):
    """
    This function generate similarity matrix.
    Every row of input matrix m represent every new label.
    """

    b, a = m.shape
    new = []
    for i in range(b):
        new.append(m[i,:])
    cosine_dist = cosine_similarity(new)
    sim_matrix = torch.from_numpy(cosine_dist)

    return sim_matrix

# def gen_sim(m):
#     I = np.identity(m.shape[0])
#     sim = np.maximum(I, np.dot(m, np.transpose(m)))
#     sim_matrix = torch.from_numpy(sim)
#     return sim_matrix

def get_labels(label):
  
  label2index = dict()
  index2label = dict()
  for idx, element in enumerate(label):
    label2index[element] = idx
    index2label[idx] = element

  return label2index, index2label

def _print(self):
    def print_node(node, indent):
        if isinstance(node, CoverTree._LeafNode):
            print ("-" * indent, node)
        else:
            print ("-" * indent, node)
            for child in node.children:
                print_node(child, indent + 1)
    print_node(self.root, 0)

def path(self):

    pathes = []
    path_tmp = []

    def _path(node, path_tmp):
        
        if isinstance(node, CoverTree._LeafNode):
            for number in node.idx:
                path_tmp.append(number)
                pathes.append(list(path_tmp))
                path_tmp.pop()
        else:
            path_tmp.append(node.ctr_idx)
            for child in node.children:
                _path(child, path_tmp)
            path_tmp.pop()

    _path(self.root, path_tmp)

    return pathes

def norm(x):
    m = np.max(x)
    n = np.min(x)
    x = (x-n) / (m-n)
    return x

class AverageMeter(object):
    """Computes and stores the average and current value"""

    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count


def accuracy(output, target, topk=(1,)):
    """Computes the precision@k for the specified values of k"""
    maxk = max(topk)
    batch_size = target.size(0)
    _, pred = output.topk(maxk, 1, largest=True, sorted=True)
    pred = pred.t()
    correct = pred.eq(target.view(1, -1).expand_as(pred))

    res = []
    for k in topk:
        correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
        res.append(correct_k.mul_(100.0 / batch_size))
    return res


def save_checkpoint(state, is_best, filename='alex_checkpoint.pth'):
    torch.save(state, filename)
    if is_best:
        shutil.copyfile(filename, 'alex_model_best.pth')


def adjust_learning_rate(optimizer, epoch, init_lr):
    """Sets the learning rate to the initial LR decayed by 10 every 30 epochs"""
    lr = init_lr * (0.1 ** (epoch // 30))
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr